version: '3.7'

services:

  postgres-db:
    container_name: postgres-db-container
    image: postgres:${POSTGRES_VERSION:-10.5}
    expose:
      - 5432
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_NAME:-afiliora}
      - POSTGRES_USER=${DB_USERNAME:-afiliora}
      - POSTGRES_DB=${DB_PASSWORD:-afiliora_db}
    restart: unless-stopped
    networks:
      - afiliora-backend

  afiliora-server:
    container_name: afiliora-application-container
    build:
      context: .
    image: afiliora-application:${APPLICATION_VERSION:-1.0}
    expose:
      - 8081
    ports:
      - ${APPLICATION_PORT:-8081}:8081
    environment:
      - DB_URL=${DB_URL:-postgres-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-afiliora_db}
      - DB_USERNAME=${DB_USERNAME:-afiliora}
      - DB_PASSWORD=${DB_PASSWORD:-afiliora}
    depends_on:
      - postgres-db
    links:
      - postgres-db
    networks:
      - afiliora-backend

volumes:
  postgres-db-volume:

networks:
  afiliora-backend:
    driver: bridge
