version: '3.7'

services:

  postgres-db:
    container_name: postgres-db-container
    image: postgres:${POSTGRES_VERSION:-10.5}
    expose:
      - 5432
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_NAME:-affiliora}
      - POSTGRES_USER=${DB_USERNAME:-affiliora}
      - POSTGRES_DB=${DB_PASSWORD:-affiliora_db}
    restart: unless-stopped
    networks:
      - affiliora-backend

  affiliora-server:
    container_name: affiliora-application-container
    build:
      context: .
    image: affiliora-application:${APPLICATION_VERSION:-1.0}
    expose:
      - 8081
    ports:
      - ${APPLICATION_PORT:-8081}:8081
    environment:
      - DB_URL=${DB_URL:-postgres-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-affiliora_db}
      - DB_SCHEMA=${DB_SCHEMA:-public}
      - DB_USERNAME=${DB_USERNAME:-affiliora}
      - DB_PASSWORD=${DB_PASSWORD:-affiliora}
      - DEVTOOLS_ENABLED=${DEVTOOLS_ENABLED:-false}
    depends_on:
      - postgres-db
    links:
      - postgres-db
    networks:
      - affiliora-backend

volumes:
  postgres-db-volume:

networks:
  affiliora-backend:
    driver: bridge
