server:
  port: 8081
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  application:
    name: afiliora-application
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  datasource:
    jdbc-url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:afiliora_db}
    username: ${DB_USERNAME:afiliora}
    password: ${DB_PASSWORD:afiliora}