server:
  port: 8081

spring:
  application:
    name: afiliora-application
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:6432}/${DB_NAME:afiliora_db}
    username: ${DB_USERNAME:afiliora}
    password: ${DB_PASSWORD:afiliora}