server:
  port: 8081
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:

  application:
    name: affiliora-application

  banner:
    location: classpath:banner.txt

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

  datasource:
    jdbc-url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:affiliora_db}?currentSchema=${DB_SCHEMA:core}
    username: ${DB_USERNAME:affiliora}
    password: ${DB_PASSWORD:affiliora}

    spring:
      devtools:
        add-properties: ${DEVTOOLS_ENABLED:false}

affiliora:
  mvc:
    enabled: ${AFFILIORA_MVC_ENABLED:true}
    cache-max-minutes: ${AFFILIORA_MVC_CACHE_MAX_MINUTES:1}